import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import Header from '@/components/organisms/header';
import Footer from '@/components/organisms/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`font-roboto ${inter.className}`}>
        <div className='flex flex-col mx-auto min-h-screen'>
          <Header />
          <main className='h-full w-full grow-1'>{children}</main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
